name: attendance_system
description: "A new Flutter project for Attendance System."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.11.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.2

  # State management / utilities
  provider: ^6.1.2
  intl: ^0.20.2
  google_fonts: ^6.2.1

  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true